### ISSUE TITLE
CSS doesn't contain the right relative font path

### ISSUE THREAD

**Issue by denizdogan** [gabiseabra/fontello-webpack-plugin#6]
Using this configuration:

```js
new FontelloPlugin({
  config: require('./fontello.config.json'),
  output: {
    css: 'css/[name].css',
    font: 'fonts/[name].[ext]'
  }
})
```

This generates this directory structure:

```
public/
  css/
    icons.css
  fonts/
    icons.svg
    icons.ttf
    ...
```

However, the CSS is generated with this incorrect font path:

```css
@font-face {
	font-family: "Icons";
	src: url("./fonts/icons.eot");
	src: url("./fonts/icons.eot") format("embedded-opentype"),
		url("./fonts/icons.woff2") format("woff2"),
		url("./fonts/icons.woff") format("woff"),
		url("./fonts/icons.ttf") format("truetype"),
		url("./fonts/icons.svg") format("svg");
	font-weight: normal;
	font-style: normal;
}
```

It should be `url("..fonts/icons.svg")` etc.
